version: "3.9"

services:
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - "redis-data:/data"
    ports:
      - "6380:${REDIS_PORT}"
    restart: always
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD} --loglevel warning

  app:
    build: .
    container_name: application
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    environment:
      REDIS_HOST: redis
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local